spring:
    datasource:
        url: jdbc:h2:mem::livraria
        username: root
        password: 
        driverClassName: org.h2.Driver
    jpa:
        hibernate:            
            database-platform: org.hibernate.dialect.H2Dialect
            show-sql: true
            format-sql: true
            #ddl-auto: create-drop
    h2:
        console:
            enabled: true
            path: /h2
            